export interface DialCode {
  /** Ülke arama kodu, ör. "+90" */
  code: string
  /** ISO 3166-1 alpha-2, ör. "TR" */
  iso2: string
  /** Türkçe ülke adı */
  name: string
}

/** Ülke arama kodları. Türkiye ilk (varsayılan). */
export const DIAL_CODES: DialCode[] = [
  { code: '+90', iso2: 'TR', name: 'Türkiye' },
  // ... Türkçe alfabetik
  { code: '+93', iso2: 'AF', name: 'Afganistan' },
  { code: '+49', iso2: 'DE', name: 'Almanya' },
  { code: '+1', iso2: 'US', name: 'Amerika Birleşik Devletleri' },
  { code: '+376', iso2: 'AD', name: 'Andorra' },
  { code: '+244', iso2: 'AO', name: 'Angola' },
  { code: '+1', iso2: 'AG', name: 'Antigua ve Barbuda' },
  { code: '+54', iso2: 'AR', name: 'Arjantin' },
  { code: '+355', iso2: 'AL', name: 'Arnavutluk' },
  { code: '+297', iso2: 'AW', name: 'Aruba' },
  { code: '+61', iso2: 'AU', name: 'Avustralya' },
  { code: '+43', iso2: 'AT', name: 'Avusturya' },
  { code: '+994', iso2: 'AZ', name: 'Azerbaycan' },
  { code: '+1', iso2: 'BS', name: 'Bahamalar' },
  { code: '+973', iso2: 'BH', name: 'Bahreyn' },
  { code: '+880', iso2: 'BD', name: 'Bangladeş' },
  { code: '+1', iso2: 'BB', name: 'Barbados' },
  { code: '+32', iso2: 'BE', name: 'Belçika' },
  { code: '+501', iso2: 'BZ', name: 'Belize' },
  { code: '+229', iso2: 'BJ', name: 'Benin' },
  { code: '+1', iso2: 'BM', name: 'Bermuda' },
  { code: '+975', iso2: 'BT', name: 'Butan' },
  { code: '+971', iso2: 'AE', name: 'Birleşik Arap Emirlikleri' },
  { code: '+44', iso2: 'GB', name: 'Birleşik Krallık' },
  { code: '+591', iso2: 'BO', name: 'Bolivya' },
  { code: '+387', iso2: 'BA', name: 'Bosna-Hersek' },
  { code: '+267', iso2: 'BW', name: 'Botsvana' },
  { code: '+55', iso2: 'BR', name: 'Brezilya' },
  { code: '+673', iso2: 'BN', name: 'Brunei' },
  { code: '+359', iso2: 'BG', name: 'Bulgaristan' },
  { code: '+226', iso2: 'BF', name: 'Burkina Faso' },
  { code: '+257', iso2: 'BI', name: 'Burundi' },
  { code: '+1', iso2: 'KY', name: 'Cayman Adaları' },
  { code: '+238', iso2: 'CV', name: 'Cabo Verde' },
  { code: '+253', iso2: 'DJ', name: 'Cibuti' },
  { code: '+235', iso2: 'TD', name: 'Çad' },
  { code: '+420', iso2: 'CZ', name: 'Çekya' },
  { code: '+86', iso2: 'CN', name: 'Çin' },
  { code: '+45', iso2: 'DK', name: 'Danimarka' },
  { code: '+670', iso2: 'TL', name: 'Doğu Timor' },
  { code: '+1', iso2: 'DO', name: 'Dominik Cumhuriyeti' },
  { code: '+1', iso2: 'DM', name: 'Dominika' },
  { code: '+593', iso2: 'EC', name: 'Ekvador' },
  { code: '+240', iso2: 'GQ', name: 'Ekvator Ginesi' },
  { code: '+503', iso2: 'SV', name: 'El Salvador' },
  { code: '+291', iso2: 'ER', name: 'Eritre' },
  { code: '+374', iso2: 'AM', name: 'Ermenistan' },
  { code: '+372', iso2: 'EE', name: 'Estonya' },
  { code: '+251', iso2: 'ET', name: 'Etiyopya' },
  { code: '+679', iso2: 'FJ', name: 'Fiji' },
  { code: '+63', iso2: 'PH', name: 'Filipinler' },
  { code: '+970', iso2: 'PS', name: 'Filistin' },
  { code: '+245', iso2: 'GW', name: 'Gine-Bissau' },
  { code: '+224', iso2: 'GN', name: 'Gine' },
  { code: '+33', iso2: 'FR', name: 'Fransa' },
  { code: '+241', iso2: 'GA', name: 'Gabon' },
  { code: '+220', iso2: 'GM', name: 'Gambiya' },
  { code: '+233', iso2: 'GH', name: 'Gana' },
  { code: '+995', iso2: 'GE', name: 'Gürcistan' },
  { code: '+1', iso2: 'GD', name: 'Grenada' },
  { code: '+299', iso2: 'GL', name: 'Grönland' },
  { code: '+502', iso2: 'GT', name: 'Guatemala' },
  { code: '+44', iso2: 'GG', name: 'Guernsey' },
  { code: '+592', iso2: 'GY', name: 'Guyana' },
  { code: '+27', iso2: 'ZA', name: 'Güney Afrika' },
  { code: '+82', iso2: 'KR', name: 'Güney Kore' },
  { code: '+211', iso2: 'SS', name: 'Güney Sudan' },
  { code: '+509', iso2: 'HT', name: 'Haiti' },
  { code: '+91', iso2: 'IN', name: 'Hindistan' },
  { code: '+385', iso2: 'HR', name: 'Hırvatistan' },
  { code: '+31', iso2: 'NL', name: 'Hollanda' },
  { code: '+504', iso2: 'HN', name: 'Honduras' },
  { code: '+852', iso2: 'HK', name: 'Hong Kong' },
  { code: '+964', iso2: 'IQ', name: 'Irak' },
  { code: '+1', iso2: 'JM', name: 'Jamaika' },
  { code: '+81', iso2: 'JP', name: 'Japonya' },
  { code: '+1', iso2: 'VG', name: 'Britanya Virjin Adaları' },
  { code: '+34', iso2: 'ES', name: 'İspanya' },
  { code: '+972', iso2: 'IL', name: 'İsrail' },
  { code: '+46', iso2: 'SE', name: 'İsveç' },
  { code: '+41', iso2: 'CH', name: 'İsviçre' },
  { code: '+39', iso2: 'IT', name: 'İtalya' },
  { code: '+354', iso2: 'IS', name: 'İzlanda' },
  { code: '+353', iso2: 'IE', name: 'İrlanda' },
  { code: '+98', iso2: 'IR', name: 'İran' },
  { code: '+855', iso2: 'KH', name: 'Kamboçya' },
  { code: '+237', iso2: 'CM', name: 'Kamerun' },
  { code: '+1', iso2: 'CA', name: 'Kanada' },
  { code: '+382', iso2: 'ME', name: 'Karadağ' },
  { code: '+974', iso2: 'QA', name: 'Katar' },
  { code: '+254', iso2: 'KE', name: 'Kenya' },
  { code: '+357', iso2: 'CY', name: 'Kıbrıs' },
  { code: '+996', iso2: 'KG', name: 'Kırgızistan' },
  { code: '+686', iso2: 'KI', name: 'Kiribati' },
  { code: '+57', iso2: 'CO', name: 'Kolombiya' },
  { code: '+269', iso2: 'KM', name: 'Komorlar' },
  { code: '+242', iso2: 'CG', name: 'Kongo Cumhuriyeti' },
  { code: '+243', iso2: 'CD', name: 'Kongo Demokratik Cumhuriyeti' },
  { code: '+383', iso2: 'XK', name: 'Kosova' },
  { code: '+506', iso2: 'CR', name: 'Kosta Rika' },
  { code: '+965', iso2: 'KW', name: 'Kuveyt' },
  { code: '+850', iso2: 'KP', name: 'Kuzey Kore' },
  { code: '+389', iso2: 'MK', name: 'Kuzey Makedonya' },
  { code: '+53', iso2: 'CU', name: 'Küba' },
  { code: '+856', iso2: 'LA', name: 'Laos' },
  { code: '+266', iso2: 'LS', name: 'Lesotho' },
  { code: '+371', iso2: 'LV', name: 'Letonya' },
  { code: '+231', iso2: 'LR', name: 'Liberya' },
  { code: '+218', iso2: 'LY', name: 'Libya' },
  { code: '+423', iso2: 'LI', name: 'Lihtenştayn' },
  { code: '+370', iso2: 'LT', name: 'Litvanya' },
  { code: '+961', iso2: 'LB', name: 'Lübnan' },
  { code: '+352', iso2: 'LU', name: 'Lüksemburg' },
  { code: '+36', iso2: 'HU', name: 'Macaristan' },
  { code: '+261', iso2: 'MG', name: 'Madagaskar' },
  { code: '+853', iso2: 'MO', name: 'Makao' },
  { code: '+265', iso2: 'MW', name: 'Malavi' },
  { code: '+960', iso2: 'MV', name: 'Maldivler' },
  { code: '+60', iso2: 'MY', name: 'Malezya' },
  { code: '+223', iso2: 'ML', name: 'Mali' },
  { code: '+356', iso2: 'MT', name: 'Malta' },
  { code: '+692', iso2: 'MH', name: 'Marshall Adaları' },
  { code: '+52', iso2: 'MX', name: 'Meksika' },
  { code: '+20', iso2: 'EG', name: 'Mısır' },
  { code: '+691', iso2: 'FM', name: 'Mikronezya' },
  { code: '+976', iso2: 'MN', name: 'Moğolistan' },
  { code: '+373', iso2: 'MD', name: 'Moldova' },
  { code: '+377', iso2: 'MC', name: 'Monako' },
  { code: '+222', iso2: 'MR', name: 'Moritanya' },
  { code: '+230', iso2: 'MU', name: 'Mauritius' },
  { code: '+258', iso2: 'MZ', name: 'Mozambik' },
  { code: '+95', iso2: 'MM', name: 'Myanmar' },
  { code: '+264', iso2: 'NA', name: 'Namibya' },
  { code: '+674', iso2: 'NR', name: 'Nauru' },
  { code: '+977', iso2: 'NP', name: 'Nepal' },
  { code: '+227', iso2: 'NE', name: 'Nijer' },
  { code: '+234', iso2: 'NG', name: 'Nijerya' },
  { code: '+505', iso2: 'NI', name: 'Nikaragua' },
  { code: '+47', iso2: 'NO', name: 'Norveç' },
  { code: '+236', iso2: 'CF', name: 'Orta Afrika Cumhuriyeti' },
  { code: '+998', iso2: 'UZ', name: 'Özbekistan' },
  { code: '+92', iso2: 'PK', name: 'Pakistan' },
  { code: '+680', iso2: 'PW', name: 'Palau' },
  { code: '+507', iso2: 'PA', name: 'Panama' },
  { code: '+675', iso2: 'PG', name: 'Papua Yeni Gine' },
  { code: '+595', iso2: 'PY', name: 'Paraguay' },
  { code: '+51', iso2: 'PE', name: 'Peru' },
  { code: '+48', iso2: 'PL', name: 'Polonya' },
  { code: '+1', iso2: 'PR', name: 'Porto Riko' },
  { code: '+351', iso2: 'PT', name: 'Portekiz' },
  { code: '+40', iso2: 'RO', name: 'Romanya' },
  { code: '+250', iso2: 'RW', name: 'Ruanda' },
  { code: '+7', iso2: 'RU', name: 'Rusya' },
  { code: '+1', iso2: 'KN', name: 'Saint Kitts ve Nevis' },
  { code: '+1', iso2: 'LC', name: 'Saint Lucia' },
  { code: '+1', iso2: 'VC', name: 'Saint Vincent ve Grenadinler' },
  { code: '+685', iso2: 'WS', name: 'Samoa' },
  { code: '+239', iso2: 'ST', name: 'São Tomé ve Príncipe' },
  { code: '+221', iso2: 'SN', name: 'Senegal' },
  { code: '+248', iso2: 'SC', name: 'Seyşeller' },
  { code: '+232', iso2: 'SL', name: 'Sierra Leone' },
  { code: '+65', iso2: 'SG', name: 'Singapur' },
  { code: '+381', iso2: 'RS', name: 'Sırbistan' },
  { code: '+421', iso2: 'SK', name: 'Slovakya' },
  { code: '+386', iso2: 'SI', name: 'Slovenya' },
  { code: '+677', iso2: 'SB', name: 'Solomon Adaları' },
  { code: '+252', iso2: 'SO', name: 'Somali' },
  { code: '+94', iso2: 'LK', name: 'Sri Lanka' },
  { code: '+249', iso2: 'SD', name: 'Sudan' },
  { code: '+597', iso2: 'SR', name: 'Surinam' },
  { code: '+963', iso2: 'SY', name: 'Suriye' },
  { code: '+966', iso2: 'SA', name: 'Suudi Arabistan' },
  { code: '+268', iso2: 'SZ', name: 'Esvatini' },
  { code: '+56', iso2: 'CL', name: 'Şili' },
  { code: '+992', iso2: 'TJ', name: 'Tacikistan' },
  { code: '+255', iso2: 'TZ', name: 'Tanzanya' },
  { code: '+66', iso2: 'TH', name: 'Tayland' },
  { code: '+886', iso2: 'TW', name: 'Tayvan' },
  { code: '+228', iso2: 'TG', name: 'Togo' },
  { code: '+676', iso2: 'TO', name: 'Tonga' },
  { code: '+1', iso2: 'TT', name: 'Trinidad ve Tobago' },
  { code: '+216', iso2: 'TN', name: 'Tunus' },
  { code: '+993', iso2: 'TM', name: 'Türkmenistan' },
  { code: '+688', iso2: 'TV', name: 'Tuvalu' },
  { code: '+256', iso2: 'UG', name: 'Uganda' },
  { code: '+380', iso2: 'UA', name: 'Ukrayna' },
  { code: '+968', iso2: 'OM', name: 'Umman' },
  { code: '+598', iso2: 'UY', name: 'Uruguay' },
  { code: '+678', iso2: 'VU', name: 'Vanuatu' },
  { code: '+379', iso2: 'VA', name: 'Vatikan' },
  { code: '+58', iso2: 'VE', name: 'Venezuela' },
  { code: '+84', iso2: 'VN', name: 'Vietnam' },
  { code: '+967', iso2: 'YE', name: 'Yemen' },
  { code: '+64', iso2: 'NZ', name: 'Yeni Zelanda' },
  { code: '+30', iso2: 'GR', name: 'Yunanistan' },
  { code: '+260', iso2: 'ZM', name: 'Zambiya' },
  { code: '+263', iso2: 'ZW', name: 'Zimbabve' },
]

/** Varsayılan arama kodu (Türkiye). */
export const DEFAULT_DIAL = '+90'
